services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-network
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    networks:
      - local-network
    ports:
      - "3000:3000"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  postgres-data:
  prometheus-data: {}

networks:
  local-network:
    driver: bridge