global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app_metrics'

    metrics_path: '/actuator/prometheus'

    static_configs:
      - targets:
        - host.docker.internal:8080
        labels:
          application: 'wallet-service'

    basic_auth:
      username: 'prometheus'
      password: 'prometheus'