CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    wallet_id BIGINT NOT NULL,
    reference_id UUID,
    amount NUMERIC(19,2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id),
    CONSTRAINT ck_transactions_amount CHECK (amount <> 0),
    CONSTRAINT ck_transactions_type CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER')),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX idx_transactions_wallet_id_created_at ON transactions(wallet_id, created_at);
CREATE INDEX idx_transactions_reference_id ON transactions(reference_id);

