CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key UUID NOT NULL,
    user_public_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    response TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT ux_idempotency_keys_user_public_id_idempotency_key UNIQUE (user_public_id, idempotency_key),
    CONSTRAINT ck_idempotency_keys_status CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX idx_idempotency_keys_created_at ON idempotency_keys(created_at);